media_folder: '/src/assets/images/uploads'
public_folder: '/src/assets/images/uploads'

# Use DecapBridge classic auth (required)
backend:
  name: git-gateway
  repo: rodnye/literary-blog
  branch: editorial_workflow
  identity_url: https://auth.decapbridge.com/sites/b83df415-5007-4469-9ae1-2ae13f23d4e1
  gateway_url: https://gateway.decapbridge.com

  # See who did what (optional)
  commit_messages:
    create: "blog: create “{{slug}}” - {{author-name}} via DecapBridge"
    update: "blog: update “{{slug}}” - {{author-name}} via DecapBridge"
    delete: "blog: delete “{{slug}}” - {{author-name}} via DecapBridge"
    uploadMedia: "blog: upload “{{path}}” - {{author-name}} via DecapBridge"
    deleteMedia: "blog: delete “{{path}}” - {{author-name}} via DecapBridge"
    openAuthoring: "blog: message {{message}} - {{author-name}} via DecapBridge"

# Better Decap + Bridge logo (optional)
logo_url: https://decapbridge.com/decapcms-with-bridge.svg

# Add site links in Decap CMS (optional)
site_url: https://quemeimporta.pages.dev

collections:
  - name: 'blog' # Used in routes, e.g., /admin/collections/blog
    label: 'Blog' # Used in the UI
    folder: 'src/content/blog' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Título', name: 'title', widget: 'string' }
      - {
          label: 'Descripción o pequeño resumen',
          name: 'description',
          widget: 'string',
        }
      - { label: 'Fecha de publicación', name: 'pubDate', widget: 'datetime' }
      - { label: 'Imagen de portada', name: 'heroImage', widget: 'image' }
      - { label: 'Contenido', name: 'body', widget: 'markdown' }
